model: jaxnerf_torch
dataset_type: blender
no_batching: true
factor: 0

num_coarse_samples: 192
num_fine_samples: 384

N_rand: 4096
use_viewdirs: true
white_bkgd: true
perturb: 1.

lr_init: 5.0e-4
lr_final: 5.0e-6
lr_delay_steps: 2500
lr_delay_mult: 0.1
max_steps: 200000

i_print: 100
i_weights: 50000
use_pixel_centers: true

chunk: 2048

netwidth: 512
netwidth_fine: 512

