model: jaxnerf_torch
dataset_type: llff
no_batching: false

num_coarse_samples: 64
num_fine_samples: 128

use_viewdirs: true

N_rand: 4096
perturb: 1.0

factor: 4
llffhold: 8
raw_noise_std: 1.

lr_init: 2.5e-4
lr_final: 2.5e-6
max_steps: 200000
lr_delay_steps: 250
lr_delay_mult: 0.1

i_print: 100
i_weights: 50000
use_pixel_centers: true

netwidth: 256
netwidth_fine: 256

no_ndc: false